name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0

      - name: Build
        shell: bash
        run: rojo build -o game.rbxl

      - name: Publish
        shell: bash
        env:
          UID: 7280890206             # Universe ID
          PID: 137811888087932        # Place ID
          API_KEY: ${{ secrets.GAME_DEPLOY_KEY_PROD }} # API Key (keep this in your GitHub Repository Secrets)
          FILE: game.rbxl         # Roblox place file (e.g. might have a step before this to build the file with Rojo)

        run: rbxcloud experience publish -a "$API_KEY" -u "$UID" -p "$PID" -t published -f "$FILE"